Repository mmcmd/verification-bot, pull requests merged in 2019-10, with the labels that each got.

#1 Added discord ext commands, removes colored roles from unboosters
  config.json
  config.json.example
  verif.py
Labels: enhancement

#2 Added unboost log channel and fixed unboosting function
  config.json.example
  verif.py
Labels: bug, enhancement

#4 Added birthday command
  config.json.example
  verif.py
Labels: enhancement

#5 Verification age requirement added to config file
  config.json.example
  verif.py
Labels: enhancement

#6 Tweaked the birthday command
  verif.py
Labels: bug, enhancement

#7 Added uptime, github and boosters command
  verif.py
Labels: enhancement

#11 Bug fixes & improvements
  verif.py
Labels: bug

#17 changed % string formatting to .format()
  resources/messages.json
  verif.py
Labels: bug, enhancement
